Project Structure
├── app.py                     # Streamlit application
├── requirements.txt           # Python dependencies
├── notebooks/
│   └── train_model.ipynb      # Data prep, training, evaluation
├── model/
│   └── apple_model.h5        # Trained model (generated by the notebook)
└── README.md
Dataset
PlantVillage dataset (Kaggle) — Apple_healthy and Apple_rotten classes.
